apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: meu-projeto
type: Opaque
data:
  DB_USER: dXNlcg==         # base64
  DB_PASSWORD: cGFzc3dvcmQ=    # base64
  DB_NAME: cGhhcm1hZmxvd19kYg==          # base64