version: '3.9'

services:
  backend:
    image: myszka/pharmaflow-backend:latest
    container_name: pharma_backend
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db
    depends_on:
      - db

  frontend:
    image: myszka/pharmaflow-frontend:latest
    container_name: pharma_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:18-alpine
    container_name: pharma_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pharmaflow_db
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data: